name: ci

on: push

env:
  GITHUB_TOKEN: ${{ secrets.issue_github_token }}
  PYTHONUNBUFFERED: 1

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Edit version for release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          CCB_VERSION=${GITHUB_REF:10}
          echo "Version: $CCB_VERSION"
          sed -i "s/\"0.0.0\"/\"$CCB_VERSION\"/" ccb/_version.py

      - name: Install CCB locally
        run: python3 -m pip install .

      - name: Pylint
        run: |
          python3 -m pip install pylint
          pylint ccb

      - name: Clone CCI
        run: |
          git clone https://qchateau:$GITHUB_TOKEN@github.com/conan-center-bot-testing/conan-center-index.git
          cd conan-center-index
          git remote add upstream https://github.com/conan-io/conan-center-index.git
          git fetch upstream
          git checkout upstream/master
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Update dev issues
        run: |
          conan-center-bot update-status-issue \
            --cci conan-center-index \
            --github-token "$GITHUB_TOKEN" \
            --force \
            --push-to origin \
            https://github.com/qchateau/conan-center-bot/issues/4

      - name: Package
        run: python3 setup.py sdist

      - name: Install twine
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: python3 -m pip install twine

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
