name: update_issue

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.issue_github_token }}
  PYTHONUNBUFFERED: 1

jobs:
  update_issue:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")

      - name: Configure ccache cache files
        uses: actions/cache@v1.1.0
        with:
          path: ~/.ccache
          key: ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ccache-

      - name: Install and configure ccache
        run: |
          sudo apt-get install ccache
          ccache --version
          ccache -s
          echo "/usr/lib/ccache" >> $GITHUB_PATH

      - name: Install and configure conan
        run: |
          python3 -m pip install conan
          conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
          conan config set hooks.conan-center
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan profile show default

      - name: Install CCB
        run: python3 -m pip install conan-center-bot

      - name: Clone CCI
        run: |
          git clone https://qchateau:$GITHUB_TOKEN@github.com/qchateau/conan-center-index.git
          cd conan-center-index
          git remote add upstream https://github.com/conan-io/conan-center-index.git
          git fetch upstream
          git checkout upstream/master
          git config --global user.email "quentin.chateau@gmail.com"
          git config --global user.name "Quentin Chateau via Conan Center Bot"

      - name: Update recipes
        run: |
          conan-center-bot auto-update-recipes \
            --cci conan-center-index \
            --github-token "$GITHUB_TOKEN" \
            --force \
            --push-to origin \
            > ./update_status.json
          cat ./update_status.json

      - name: Update status issue
        run: |
          conan-center-bot update-status-issue \
            --github-token "$GITHUB_TOKEN" \
            ./update_status.json \
            https://github.com/qchateau/conan-center-bot/issues/1 \
            https://github.com/conan-io/conan-center-index/issues/3470
