name: update_issue

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.issue_github_token }}

jobs:
  update_issue:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone CCI
        run: git clone https://github.com/conan-io/conan-center-index.git --depth 1

      - name: Update CCI status issues
        run: |
          python3 -m venv .venv && source .venv/bin/activate
          python3 -m pip install conan-center-bot
          conan-center-bot update-status-issue \
            --cci conan-center-index \
            --github-token "$GITHUB_TOKEN" \
            https://github.com/qchateau/conan-center-bot/issues/1 \
            https://github.com/conan-io/conan-center-index/issues/3470
