name: update_issue

on:
  schedule:
    - cron: "0 2 * * *"
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.issue_github_token }}

jobs:
  update_issue:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/conan-io/conan-center-index.git --depth 1
      - run: python3 -m pip install -r requirements.txt

      - if: ${{ github.ref == 'refs/heads/master' }}
        run: >-
          python3 ./main.py update-status-issue
          --cci conan-center-index
          --github-token "$GITHUB_TOKEN"
          https://github.com/qchateau/conan-center-bot/issues/1
          https://github.com/conan-io/conan-center-index/issues/3470

      - if: ${{ github.ref != 'refs/heads/master' }}
        run: >-
          python3 ./main.py update-status-issue
          --cci conan-center-index
          --github-token "$GITHUB_TOKEN"
          https://github.com/qchateau/conan-center-bot/issues/4
